apiVersion: v1
kind: Pod
metadata:
  name: alpine3
spec:
  containers:
  - name: alpine3
    image: alpine
    command:
    - "sleep"
    - "10000"
    env:
    - name: MONGO_URL
      valueFrom:
        secretKeyRef:
          name: mongo-creds
          key: mongoURL